# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
#
{
    'name': 'Tent',
    'version': '1.0',
    'depends': ['base','product','sale_stock','report_extended'],
    'author': 'Sofco',
    'category': '',
    'description': """
    Módulo de Carpa 
    """,
    'update_xml': [],
    "data" : [  
        "security/tent_security.xml",
        "security/ir.model.access.csv",
        "tent_view.xml",
        "hotel_tent_reservation_sequence.xml",
        "views/max_tent.xml",
        "views/report_checkin.xml",
        "views/report_checkout.xml",
        "views/tent_res.xml",
        "views/tent_summ_view.xml",
        "wizard/tent_wizard.xml",
        "report/tent_report.xml",
        ],
    'js': ["static/src/js/tent_summary.js"],
    'qweb': ['static/src/xml/tent_summary.xml'],
    'css': ["static/src/css/tent_summary.css"],
    'installable': True,
    'auto_install': False,
}
