# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
#
{
    'name': 'Toldo Reservation',
    'version': '1.0',
    'depends': ['base','product','stock','sale_stock','report_extended','account','toldo'],
    'author': 'Sofco',
    'category': 'Generic Modules/Toldo Reservation',
    'description': """
    Módulo de reservacion de Toldo 
    """,
    'update_xml': [],
    "data" : [  
        "wizard/toldo_reservation_wizard.xml",
        "report/toldo_reservation_report.xml",
        "awning_reservation_sequence.xml",
        "awning_reservation_view.xml",
        "views/report_checkin.xml",
        "views/report_checkout.xml",
        "views/max_awning.xml",
        "views/awning_res.xml",
        "views/awning_summ_view.xml",
        "security/ir.model.access.csv"
        ],
    "demo": [
        'toldo_reservation_data.xml',
    ],
    'js': ["static/src/js/toldo_awning_summary.js", ],
    'qweb': ['static/src/xml/toldo_awning_summary.xml'],
    'css': ["static/src/css/awning_summary.css"],
    'installable': True,
    'auto_install': False,
}
